#!/usr/bin/perl

use warnings;
use strict;

my $mutation = $ARGV[0];
my $mut_pos = $ARGV[1];
my $mut_length = $ARGV[2];

system("./XS -ls 50 -n 10000 -eh -eo -es -f 0.3,0.2,0.2,0.3,0.0 reference_seq.fasta");
system("./mutator reference_seq.fasta $mutation $mut_pos $mut_length > mutated.fasta");
system("sed -i '1s/^/>Ref_seq\n/' file.txt");
system("./art_illumina -ss MSv1 -M -p -na -k 0 -i mutated.fasta -l 150 -f 30 -m 200 -s 10 -o reads_");

system("bwa index reference_seq.fasta");
system("bwa mem reference_seq.fasta reads_1.fastq reads_1.fastq > alingment.sam");
system("samtools view -b -S alingment.sam > reads_aligned.bam");
system("samtools sort reads_aligned.bam reads_sorted");
system("java -jar ../picard.jar CreateSequenceDictionary R=reference_seq.fasta O=reference_seq.dict");
system("samtools faidx reference_seq.fasta");
system("java -jar picard/picard.jar AddOrReplaceReadGroups I=reads_sorted.bam O=output.bam RGID=4 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=20");
system("samtools index output.bam ");
system("mkdir VCF");
system("java -jar ../GenomeAnalysisTK.jar -T HaplotypeCaller -R reference_seq.fasta -I output.bam -dontUseSoftClippedBases -stand_call_conf 20.0 -o VCF/GATK.vcf");
system("delly call -t DEL -g output.bam -o Output.bcf");
system("bcftools view Output.bcf > VCF/DELLY.vcf");
